### ISSUE TITLE
As a pack leader, I want to log in and view the employee portal

### ISSUE THREAD

**Issue by czachary** [shstan/CS3312_Proj#32]
## Story/Task Details
- [x] If user credentials is that of a pack leader, the user is directed to the employee portal

## Acceptance Scenarios
Given: A pack leader wants to schedule available hours or view completed/upcoming walks
When: they enter their valid credentials and log in
Then: they are directed to the employee portal

Given: A pack leader wants to set available hours or view completed/upcoming walks
When: they enter invalid credentials and try to log in
Then: an error message appears that the credentials are invalid

Given: A pack leader wants to set available hours or view completed/upcoming walks
When: they enter credentials of a dog owner account
Then: they are directed to the customer portal

## Done Done Criteria
- Code is merged with sprint branch, unit tests coded and passing, and acceptance test passing

**Comment by jonesg504** [comment]
registering and logging in works for pack leaders
